import type { JobEditorField, JobEditorForm } from './types'

export function createInitialJobEditorForm(): JobEditorForm {
  return {
    id: null,
    name: '',
    node: 'hub',
    schedule: '',
    scheduleTimezone: 'UTC',
    scheduleMode: 'manual',
    simpleScheduleKind: 'daily',
    simpleEveryMinutes: 15,
    simpleAtHour: 0,
    simpleAtMinute: 0,
    simpleWeekday: 1,
    simpleMonthday: 1,
    overlapPolicy: 'queue',
    jobType: 'filesystem',
    artifactFormat: 'archive_v1',
    encryptionEnabled: false,
    encryptionKeyName: 'default',
    fsPaths: [],
    fsInclude: '',
    fsExclude: '',
    fsPreScan: true,
    fsSymlinkPolicy: 'keep',
    fsHardlinkPolicy: 'copy',
    fsErrorPolicy: 'fail_fast',
    fsSnapshotMode: 'off',
    fsSnapshotProvider: '',
    fsConsistencyPolicy: 'warn',
    fsConsistencyFailThreshold: 0,
    fsUploadOnConsistencyFailure: false,
    sqlitePath: '',
    sqliteIntegrityCheck: false,
    vaultwardenDataDir: '',
    vaultwardenConsistencyPolicy: 'warn',
    vaultwardenConsistencyFailThreshold: 0,
    vaultwardenUploadOnConsistencyFailure: false,
    targetType: 'webdav',
    webdavBaseUrl: '',
    webdavSecretName: '',
    webdavRawTreeDirectMode: 'off',
    webdavRawTreeDirectResumeBySize: true,
    webdavRawTreeDirectConcurrency: 4,
    webdavRawTreeDirectPutQps: 20,
    webdavRawTreeDirectHeadQps: 50,
    webdavRawTreeDirectMkcolQps: 50,
    webdavRawTreeDirectBurst: 10,
    localBaseDir: '',
    partSizeMiB: 256,
    notifyMode: 'inherit',
    notifyWecomBots: [],
    notifyEmails: [],
    retentionEnabled: false,
    retentionKeepLast: null,
    retentionKeepDays: null,
    retentionMaxDeletePerTick: 50,
    retentionMaxDeletePerDay: 200,
  }
}

export function resetJobEditorForm(target: JobEditorForm): void {
  Object.assign(target, createInitialJobEditorForm())
}

export function createInitialJobEditorFieldErrors(): Record<JobEditorField, string | null> {
  return {
    name: null,
    scheduleTimezone: null,
    schedule: null,
    retentionKeepLast: null,
    retentionKeepDays: null,
    retentionMaxDeletePerTick: null,
    retentionMaxDeletePerDay: null,
    fsPaths: null,
    fsSnapshotMode: null,
    fsSnapshotProvider: null,
    fsConsistencyPolicy: null,
    fsConsistencyFailThreshold: null,
    fsUploadOnConsistencyFailure: null,
    sqlitePath: null,
    vaultwardenDataDir: null,
    vaultwardenConsistencyPolicy: null,
    vaultwardenConsistencyFailThreshold: null,
    vaultwardenUploadOnConsistencyFailure: null,
    webdavBaseUrl: null,
    webdavSecretName: null,
    webdavRawTreeDirectMode: null,
    webdavRawTreeDirectConcurrency: null,
    webdavRawTreeDirectPutQps: null,
    webdavRawTreeDirectHeadQps: null,
    webdavRawTreeDirectMkcolQps: null,
    webdavRawTreeDirectBurst: null,
    localBaseDir: null,
    partSizeMiB: null,
    encryptionKeyName: null,
  }
}
